project_name: chain
env:
  - GO111MODULE=on
before:
  hooks:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
builds:
  - id: chain-darwin-amd64
    ldflags: -s -w -X github.com/Kwinin/blockchain_golang.Version={{.Version}} -X github.com/Kwinin/blockchain_golang.BuildDate={{.Date}} -X github.com/Kwinin/blockchain_golang.CommitHash={{ .ShortCommit }}
    binary: chain
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: chain-linux-amd64
    binary: chain
    env:
      - CGO_ENABLED=1
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64

  - id: chain-windows-amd64
    binary: chain
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}"
    wrap_in_directory: true
    replacements:
      macOS: darwin
      Linux: linux
      Windows: windows
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
